import { useVitalsStore } from "@/stores/VitalsStore";
import { useInvestigationStore } from "@/stores/InvestigationStore";
import { useOutcomeStore } from "@/stores/OutcomeStore";
import { useMedicationsStore } from "@/stores/MedicationsStore";
import { useTreatmentPlanStore } from "@/stores/TreatmentPlanStore";
import { useDiagnosisStore } from "@/stores/DiagnosisStore";
import { useBirthRegistrationStore } from "@/apps/Immunization/stores/BirthRegistrationStore";

import { useDemographicsStore } from "@/stores/DemographicStore";
import { useEnrollementStore } from "@/stores/EnrollmentStore";
import { useNextAppointmentStore } from "@/stores/NextAppointmentStore";
import { useRegistrationStore } from "@/stores/RegistrationStore";
import { useObstreticHistoryStore } from "@/apps/ANC/store/profile/PastObstreticHistoryStore";
import { useMedicalHistoryStore } from "@/apps/ANC/store/profile/medicalHistoryStore";
import { useWomanBehaviourStore } from "@/apps/ANC/store/profile/womanBehaviourStore";
import { useCurrentPregnanciesStore } from "@/apps/ANC/store/profile/CurrentPreganciesStore";
import { useMedicationStore } from "@/apps/ANC/store/profile/MedicationStore";
import { useAncEndStore } from "@/apps/ANC/store/ancEnd/ancEndStore";
import { useBehaviourCousellingStore } from "@/apps/ANC/store/counselling/behaviourCousellingStore";
import { useDietCounsellingStore } from "@/apps/ANC/store/counselling/dietCounsellingStore";
import { usePhysiologicalCounselingStore } from "@/apps/ANC/store/counselling/physiologicalCounselingStore";
import { useHeadssAssessmentStore } from "@/apps/ANC/store/others/headsAssessmentStore";
import { useFetalAssessment } from "@/apps/ANC/store/physical exam/FetalAssessmentStore";
import { useFetalPresentationStore } from "@/apps/ANC/store/physical exam/FetalPresantationStore";
import { usePresentingSigns } from "@/apps/ANC/store/physical exam/PresentingSignsStore";
import { useMaternalExamStore } from "@/apps/ANC/store/physical exam/MaternalExamStore";
import { useSpecificHealthConcernsStore } from "@/apps/ANC/store/quickCheck/specificHealthConcerns";
import { useReasonForVisitStore } from "@/apps/ANC/store/quickCheck/reasonForVisit";
//import { useDangerSignsStore } from "@/apps/ANC/store/Tempo";
import { useConfirmPregnancyStore } from "@/apps/ANC/store/quickCheck/confirmPregnancy";
import { useReferralStore } from "@/apps/ANC/store/referral/referralStore";
import { useIpvStore } from "@/apps/ANC/store/symptomsFollowUp/ipvStore";
import { useFatalMovementStore } from "@/apps/ANC/store/symptomsFollowUp/fatalMovementStore";
import { useCurrentPhysiologicalSymptomsStore } from "@/apps/ANC/store/symptomsFollowUp/currentPhysiologicalSymptomsStore";
import { useMedicalFollowUpStore } from "@/apps/ANC/store/symptomsFollowUp/medicalFollowUp";
import { usePersistentBehaviourStore } from "@/apps/ANC/store/symptomsFollowUp/persistentBehaviourStore";
import { useWomenBehaviourStore } from "@/apps/ANC/store/symptomsFollowUp/womenBehaviourStore";
import { useMedicStore } from "@/apps/ANC/store/symptomsFollowUp/MedicStore";
import { usePreventativeCounsellingStore } from "@/apps/ANC/store/counselling/preventativeCounsellingStore";
import { useDewormingStore } from "@/apps/ANC/store/dewormingStore";
import { useImmunizationStore } from "@/apps/ANC/store/immunizationStore";
//import { useIntimatePartnerStore } from "@/apps/ANC/store/intimatePartnerStore";
import { useLabTestsStore } from "@/apps/ANC/store/LabTestsStore";
import { useMedicationDispensedStore } from "@/apps/ANC/store/medicationDispensed";
import { useTBScreeningStore } from "@/apps/ANC/store/TBScreeningStore";
import { useUrineTestStore } from "@/apps/ANC/store/UrineTestStore";
import { useLabourObstreticHistoryStore } from "@/apps/LABOUR/stores/obstetric details/obstetric";
import { useLabourDetailsStore } from "@/apps/LABOUR/stores/obstetric details/labour";
import { useLabourQuickCheckStore } from "@/apps/LABOUR/stores/physical exam/quickCheck";
import { useLabourPhysicalExamStore } from "@/apps/LABOUR/stores/physical exam/physicalExamination";
import { usefirstVaginalExaminationStore } from "@/apps/LABOUR/stores/physical exam/firstVaginalExamination";
import { usePelvicAssessmentStore } from "@/apps/LABOUR/stores/physical exam/pelvicAssessment";
import { useEndLabourStore } from "@/apps/LABOUR/stores/repeatable things/labourAndDeliveryEnd";
import { useLabourVitalsStore } from "@/apps/LABOUR/stores/repeatable things/vitals";
import { useOtherExamsStore } from "@/apps/LABOUR/stores/repeatable things/otherExams";
import { useLabourReferralStore } from "@/apps/LABOUR/stores/repeatable things/referral";
import { useSecondStageOfLabourStore } from "@/apps/LABOUR/stores/delivery details/secondStageDelivery";
import { useThirdStageOfLabourStore } from "@/apps/LABOUR/stores/delivery details/thirdStageDelivery";
import { useImmediatePostnatalChecksForMotherStore } from "@/apps/LABOUR/stores/delivery details/immediatepostnatalChecksForMother";
import { useImmediatePostnatalChecksForChildStore } from "@/apps/LABOUR/stores/delivery details/immediatepostnatalChecksForChild";
import { useObstetricDetailsStore } from "@/apps/PNC/stores/postnatal details/ObstetricDetails";
import { useDeliveryDetailsStore } from "@/apps/PNC/stores/postnatal details/DeliveryDetails";
import { useHIVStatusAndTreatmentStore } from "@/apps/PNC/stores/postnatal details/HIVStatusAndTreatment";
import { usePostnatalWardStayStore } from "@/apps/PNC/stores/postnatal ward stay/PostnatalWardMonitoring";
import { useBabyStatusStore } from "@/apps/PNC/stores/postnatal ward stay/BabyStatus";
import { useDangerSignsStore } from "@/apps/ANC/store/quickCheck/dangerSigns";
//import { useMedicationsStore } from "@/apps/ANC/store/profile/MedicationsStore";

import { useWeightHeightVitalsStore } from "@/apps/Immunization/stores/VitalsStore";

export async function resetPatientData() {
    localStorage.setItem("saveProgressStatus", "false");
    const vitals = useVitalsStore();
    const investigations = useInvestigationStore();
    const outcome = useOutcomeStore();
    const medications = useMedicationsStore();
    const treatmentPlan = useTreatmentPlanStore();
    const diagnosis = useDiagnosisStore();
    const enrollement = useEnrollementStore();
    const nextAppointment = useNextAppointmentStore();
    const registration = useRegistrationStore();
    const weightHeightVitals = useWeightHeightVitalsStore();
    const birthRegistration = useBirthRegistrationStore();

    const ANCobstreticHistory = useObstreticHistoryStore();
    const ANCmedicalHistory = useMedicalHistoryStore();
    const ANCmedic = useMedicationStore();
    const ANCwomanBehavior = useWomanBehaviourStore();
    const ANCcurretPregnancy = useCurrentPregnanciesStore();
    const ancEnd = useAncEndStore();
    const ANCbehaviourCounselling = useBehaviourCousellingStore();
    const ANCdietCounselling = useDietCounsellingStore();
    const ANCphysCounselling = usePhysiologicalCounselingStore();
    const heads = useHeadssAssessmentStore();

    const ANCfatalAssment = useFetalAssessment();
    const ANCfatalPres = useFetalPresentationStore();
    const ANCpresSigns = usePresentingSigns();
    const ANCmaternalExam = useMaternalExamStore();
    const ANCspecifidHealthConditions = useSpecificHealthConcernsStore();
    const ANCvisits = useReasonForVisitStore();
    const ANCdangerSigns = useDangerSignsStore();
    const ANCpregnancy = useConfirmPregnancyStore();
    const ANCreferal = useReferralStore();
    const ANCstore = useIpvStore();
    const ANCfatalMovement = useFatalMovementStore();
    const ANCcurrentPhysiological = useCurrentPhysiologicalSymptomsStore();
    const ANCmedicalFollowUp = useMedicalFollowUpStore();
    const ANCpersistent = usePersistentBehaviourStore();
    const ANCwomenBehavior = useWomenBehaviourStore();
    const ANCmedication = useMedicStore();
    const ANCpreventativeCounselling = usePreventativeCounsellingStore();
    const ANCdeworming = useDewormingStore();
    const ANCdiagnosis = useDiagnosisStore();
    const ANCimmunisation = useImmunizationStore();
    //const ANCintimatePartner = useIntimatePartnerStore();
    const ANCLabTest = useLabTestsStore();
    const ANCmedicationDispensed = useMedicationDispensedStore();
    const ANCtbScreening = useTBScreeningStore();
    const ANCurineTest = useUrineTestStore();
    const exa = useHeadssAssessmentStore();

    const LabourObstreticHistory = useLabourObstreticHistoryStore();
    const LabourDetails = useLabourDetailsStore();
    const LabouruickCheckStore = useLabourQuickCheckStore();
    const LabourPhysicalExam = useLabourPhysicalExamStore();
    const LabourVaginalExamination = usefirstVaginalExaminationStore();
    const LabourPelvicAssessment = usePelvicAssessmentStore();
    const LabourVitals = useLabourVitalsStore();
    const LabourOtherExams = useOtherExamsStore();
    const LabourReferral = useLabourReferralStore();
    const LabourSecondStage = useSecondStageOfLabourStore();
    const LabourThirdStage = useThirdStageOfLabourStore();
    const LabourChecksForMother = useImmediatePostnatalChecksForMotherStore();
    const LabourChecksForChild = useImmediatePostnatalChecksForChildStore();
    const LabourEnd = useEndLabourStore();

    const PNCObstetricDetails = useObstetricDetailsStore();
    const PNCDeliveryDetails = useDeliveryDetailsStore();
    const PNCHIVStatusAndTreatment = useHIVStatusAndTreatmentStore();
    const PNCPostnatalWard = usePostnatalWardStayStore();
    const PNCBabyStatus = useBabyStatusStore();

    vitals.setVitals(vitals.getInitialVitals());
    birthRegistration.setBirthRegistration(birthRegistration.getInitialBirthRegistration());
    registration.setPersonalInformation(registration.getInitialPersonalInformation());
    registration.setSocialHistory(registration.getInitialSocialHistory());
    registration.setHomeLocation(registration.getInitialHomeLocation());
    registration.setCurrentLocation(registration.getInitialCurrentLocation());
    registration.setGuardianInformation(registration.getInitialGuardianInformation());
    registration.setCountry(registration.getInitialCountry());
    weightHeightVitals.setVitals(weightHeightVitals.getInitialVitals());

    enrollement.setDiagnosis(enrollement.getInitialEnrollmentDiagnosis());
    enrollement.setPatientHistory(enrollement.getInitialPatientHistory());
    enrollement.setSubstance(enrollement.getInitialSubstance());
    enrollement.setPatientHistory(enrollement.getInitialFamilyHistory());
    enrollement.setNCDNumber(enrollement.getInitialNCDNumber());
    enrollement.setPatientHistoryHIV(enrollement.getInitialPatientHistoryHIV());
    investigations.$reset();
    outcome.$reset();
    medications.$reset();
    treatmentPlan.$reset();
    diagnosis.$reset();
    enrollement.$reset();
    nextAppointment.$reset();

    ANCobstreticHistory.$reset();
    ANCmedicalHistory.$reset();
    ANCmedic.$reset();
    ANCwomanBehavior.$reset();
    ANCcurretPregnancy.$reset();
    ancEnd.$reset();
    ANCbehaviourCounselling.$reset();
    ANCdietCounselling.$reset();
    ANCwomanBehavior.$reset();
    ANCphysCounselling.$reset();
    heads.$reset();

    ANCfatalAssment.$reset();
    ANCfatalPres.$reset();
    ANCpresSigns.$reset();
    ANCmaternalExam.$reset();
    ANCspecifidHealthConditions.$reset();
    ANCvisits.$reset();
    ANCdangerSigns.$reset();
    ANCpregnancy.$reset();
    ANCreferal.$reset();
    ANCstore.$reset();
    ANCfatalMovement.$reset();
    ANCcurrentPhysiological.$reset();
    ANCmedicalFollowUp.$reset();
    ANCpersistent.$reset();
    ANCwomenBehavior.$reset();
    ANCmedication.$reset();
    ANCpreventativeCounselling.$reset();
    ANCdeworming.$reset();
    ANCdiagnosis.$reset();
    ANCimmunisation.$reset();
    //ANCintimatePartner.$reset();
    ANCLabTest.$reset();
    ANCmedicationDispensed.$reset();
    ANCtbScreening.$reset();
    ANCurineTest.$reset();

    LabourObstreticHistory.$reset();
    LabourDetails.$reset();
    LabouruickCheckStore.$reset();
    LabourPhysicalExam.$reset();
    LabourVaginalExamination.$reset();
    LabourPelvicAssessment.$reset();
    LabourVitals.$reset();
    LabourOtherExams.$reset();
    LabourReferral.$reset();
    LabourSecondStage.$reset();
    LabourThirdStage.$reset();
    LabourChecksForMother.$reset();
    LabourChecksForChild.$reset();
    LabourEnd.$reset();

    PNCObstetricDetails.$reset();
    PNCDeliveryDetails.$reset();
    PNCHIVStatusAndTreatment.$reset();
    PNCPostnatalWard.$reset();
    PNCBabyStatus.$reset();
}

export function resetDemographics() {
    const demographics = useDemographicsStore();
    demographics.$reset();
}
